### PR TITLE
add navbar

### PR DESCRIPTION
**Pull request by webmihail**

### CODE REVIEW

**Comment by lyzhovnik** [comment]
If you are using Create React App, try to use Css-modules which is out of the box https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet#docsNav

**Comment by lyzhovnik** [comment]
Also try to use ready made design lib, to short you time, like https://material-ui.com/ or https://ant.design/ (usually we use this for our projects)

**Comment by webmihail** [comment]
Ok. Thanks.

**Comment by lyzhovnik** [comment]
Also for commit naming use Past simple time, Like "Added navbar." with capital first letter. And the same for Pull Request name, and try to use more stateful name for branch: 'add-navbar'

**Pull request closed without merging**
